[package]
authors = ["Kyle Coffey <kylecoffey1999@gmail.com>"]
edition = "2018"
name = "rgit"
version = "0.1.0"
[dependencies]
chrono = "*"
clap = "*"
structopt = "*"
thiserror = "*"

[dependencies.git2]
version = "*"
path = "./git2-rs"
features = ["vendored-openssl"]
